version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: product_management_db
      POSTGRES_USER: PelegChen57522
      POSTGRES_PASSWORD: pkdji123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
